pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.12.20, zulu@8)
    actions:
      merge:
        method: squash
